-- Adds unified admin-managed service page content storage.

CREATE TABLE IF NOT EXISTS services_content (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    status ENUM('draft','published') NOT NULL DEFAULT 'published',
    page_title VARCHAR(255) NOT NULL,
    seo_description TEXT NULL,
    hero_eyebrow VARCHAR(255) NULL,
    hero_secondary_button_text VARCHAR(255) NULL,
    hero_secondary_button_link VARCHAR(255) NULL,
    hero_empty_note TEXT NULL,
    overview_eyebrow VARCHAR(255) NULL,
    overview_title VARCHAR(255) NOT NULL,
    overview_body TEXT NULL,
    highlight_2_title VARCHAR(255) NULL,
    highlight_2_body TEXT NULL,
    highlight_3_title VARCHAR(255) NULL,
    highlight_3_body TEXT NULL,
    content_body LONGTEXT NULL,
    benefits_eyebrow VARCHAR(255) NULL,
    benefits_title VARCHAR(255) NULL,
    feature_1 VARCHAR(255) NULL,
    feature_2 VARCHAR(255) NULL,
    feature_3 VARCHAR(255) NULL,
    feature_4 VARCHAR(255) NULL,
    feature_5 VARCHAR(255) NULL,
    sustainable_title VARCHAR(255) NULL,
    sustainable_body_1 TEXT NULL,
    sustainable_body_2 TEXT NULL,
    process_eyebrow VARCHAR(255) NULL,
    process_title VARCHAR(255) NULL,
    process_body TEXT NULL,
    step_1_title VARCHAR(255) NULL,
    step_1_body TEXT NULL,
    step_2_title VARCHAR(255) NULL,
    step_2_body TEXT NULL,
    step_3_title VARCHAR(255) NULL,
    step_3_body TEXT NULL,
    gallery_eyebrow VARCHAR(255) NULL,
    gallery_title VARCHAR(255) NULL,
    gallery_empty_note TEXT NULL,
    cta_eyebrow VARCHAR(255) NULL,
    cta_title TEXT NULL,
    cta_body TEXT NULL,
    cta_button_text VARCHAR(255) NULL,
    cta_button_link VARCHAR(255) NULL,
    support_title VARCHAR(255) NULL,
    support_body TEXT NULL,
    phone_label VARCHAR(255) NULL,
    email_label VARCHAR(255) NULL,
    contact_eyebrow VARCHAR(255) NULL,
    contact_title VARCHAR(255) NULL,
    office_eyebrow VARCHAR(255) NULL,
    office_link_1_title VARCHAR(255) NULL,
    office_link_1_body TEXT NULL,
    office_link_2_title VARCHAR(255) NULL,
    office_link_2_body TEXT NULL,
    related_eyebrow VARCHAR(255) NULL,
    related_title VARCHAR(255) NULL,
    gallery_1 VARCHAR(255) NULL,
    gallery_2 VARCHAR(255) NULL,
    gallery_3 VARCHAR(255) NULL,
    gallery_4 VARCHAR(255) NULL,
    gallery_5 VARCHAR(255) NULL,
    gallery_6 VARCHAR(255) NULL,
    sustainable_image_1 VARCHAR(255) NULL,
    sustainable_image_2 VARCHAR(255) NULL,
    cta_image VARCHAR(255) NULL,
    contact_image VARCHAR(255) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_services_content_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
